/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cecar.vista;

/**
 *
 * @author osnayder
 */
public class Vr extends javax.swing.JFrame {

    /**
     * Creates new form Vr
     */
    public Vr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Numero Cedula:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 60, 98, 30);

        jLabel2.setText("Nombres:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(46, 100, 60, 30);

        jLabel3.setText("Apellidos:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(46, 140, 60, 30);

        jLabel4.setText("Edad:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(58, 180, 40, 30);

        jLabel5.setText("Dirreccion:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(31, 220, 70, 30);

        jLabel6.setText("Tel:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(68, 260, 30, 30);

        jLabel7.setText("Cel:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(370, 60, 30, 30);

        jLabel8.setText("Otras Redes:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(330, 150, 80, 30);

        jCheckBox1.setText("WhatsApp");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(410, 150, 90, 23);

        jCheckBox2.setText("Facebook");
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(500, 150, 90, 23);

        jCheckBox3.setText("Instagram");
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(410, 170, 90, 23);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(410, 240, 150, 30);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(410, 200, 150, 30);

        jLabel9.setText("Contraseña:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(330, 200, 70, 30);

        jLabel10.setText("Repita Contraseña");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(300, 240, 110, 30);

        jButton1.setText("Cancelar");
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 310, 90, 30);

        jButton2.setText("Registrar");
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 310, 90, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 60, 150, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(130, 100, 150, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(130, 140, 150, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(130, 180, 150, 30);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(130, 220, 150, 30);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(130, 260, 150, 30);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(410, 60, 150, 30);

        jLabel11.setText("Departamento:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(320, 100, 80, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(410, 100, 150, 30);

        setSize(new java.awt.Dimension(617, 385));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
